# Generated by Django 4.1.6 on 2023-11-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanerQuest',
            fields=[
                ('movie_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='User_ID')),
                ('type', models.CharField(db_column='Type', max_length=20)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('description', models.CharField(db_column='Description', max_length=500)),
            ],
        ),
    ]
