# Generated by Django 4.1.6 on 2023-11-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planerquest',
            old_name='movie_id',
            new_name='quest_id',
        ),
    ]
